config/routes.rb
Rails.application.routes.draw do

  resources :magazines
  resources :oenologists
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  resources :wines
  resources :strains
  root 'wines#index'






end

app/models/oenologist.rb
class Oenologist < ApplicationRecord
  has_many :oenologist_magazines, dependent: :destroy
  has_many :magazines, through: :oenologist_magazines
end

app/controllers/oenologists_controller.rb
class OenologistsController < ApplicationController
  before_action :set_oenologist, only: %i[ show edit update destroy ]

  # GET /oenologists or /oenologists.json
  def index
    @oenologists = Oenologist.all
    @magazine = Magazine.all
  end

  # GET /oenologists/1 or /oenologists/1.json
  def show
  end

  # GET /oenologists/new
  def new
    @oenologist = Oenologist.new
    @magazine = Magazine.all
  end

  # GET /oenologists/1/edit
  def edit
  end

  # POST /oenologists or /oenologists.json
  def create
    @oenologist = Oenologist.new(oenologist_params)

    respond_to do |format|
      if @oenologist.save
        format.html { redirect_to @oenologist, notice: "Oenologist was successfully created." }
        format.json { render :show, status: :created, location: @oenologist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @oenologist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /oenologists/1 or /oenologists/1.json
  def update
    respond_to do |format|
      if @oenologist.update(oenologist_params)
        format.html { redirect_to @oenologist, notice: "Oenologist was successfully updated." }
        format.json { render :show, status: :ok, location: @oenologist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @oenologist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /oenologists/1 or /oenologists/1.json
  def destroy
    @oenologist.destroy
    respond_to do |format|
      format.html { redirect_to oenologists_url, notice: "Oenologist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_oenologist
      @oenologist = Oenologist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def oenologist_params
      params.require(:oenologist).permit(:name, :age, :nationality, :editor, :writer, :reviewer, magazine_ids:[])
    end
end

app/helpers/oenologists_helper.rb
module OenologistsHelper
end

app/views/oenologists/_form.html.erb
<%= form_with(model: oenologist, local: true) do |form| %>
  <% if oenologist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(oenologist.errors.count, "error") %> prohibited this oenologist from being saved:</h2>

      <ul>
      <% oenologist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :nationality %>
    <%= form.text_field :nationality %>
  </div>
  <h2>Define your Magazine</h2>
    <div class="field">
    <%= form.collection_check_boxes(:magazine_ids, Magazine.all, :id, :name) do |b|%>
      <%= b.label class: 'label-checkbox' do %>
        <%= b.check_box + b.text%>
      <% end %>
    <% end %>
  </div>


  <h2>Define your Position</h2>
  <div class="field">
    <%= form.label :editor %>
    <%= form.check_box :editor %>
  </div>

  <div class="field">
    <%= form.label :writer %>
    <%= form.check_box :writer %>
  </div>

  <div class="field">
    <%= form.label :reviewer %>
    <%= form.check_box :reviewer %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/oenologists/edit.html.erb
<h1>Editing Oenologist</h1>

<%= render 'form', oenologist: @oenologist %>

<%= link_to 'Show', @oenologist %> |
<%= link_to 'Back', oenologists_path %>

app/views/oenologists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Oenologists</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Nationality</th>
      <th>Editor</th>
      <th>Writer</th>
      <th>Reviewer</th>
      <th>Magazine</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @oenologists.each do |oenologist| %>
      <tr>
        <td><%= oenologist.name %></td>
        <td><%= oenologist.age %></td>
        <td><%= oenologist.nationality %></td>
        <td><%= oenologist.editor %></td>
        <td><%= oenologist.writer %></td>
        <td><%= oenologist.reviewer %></td>
        <td><%= oenologist.magazines.map(&:name).join(', ') %></td>       
        <td><%= link_to 'Show', oenologist %></td>
        <td><%= link_to 'Edit', edit_oenologist_path(oenologist) %></td>
        <td><%= link_to 'Destroy', oenologist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Oenologist', new_oenologist_path, class:'btn btn-dark mx-2 text-light'%>
<%= link_to 'New Magazine', new_magazine_path, class:'btn btn-dark mx-2 text-light'%>

app/views/oenologists/new.html.erb
<h1>New Oenologist</h1>

<%= render 'form', oenologist: @oenologist %>

<%= link_to 'Back', oenologists_path %>

app/views/oenologists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @oenologist.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @oenologist.age %>
</p>

<p>
  <strong>Nationality:</strong>
  <%= @oenologist.nationality %>
</p>

<p>
  <strong>Editor:</strong>
  <%= @oenologist.editor %>
</p>

<p>
  <strong>Writer:</strong>
  <%= @oenologist.writer %>
</p>

<p>
  <strong>Reviewer:</strong>
  <%= @oenologist.reviewer %>
</p>

<%= link_to 'Edit', edit_oenologist_path(@oenologist) %> |
<%= link_to 'Back', oenologists_path %>