config/routes.rb
Rails.application.routes.draw do

  resources :magazines
  resources :oenologists
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  resources :wines
  resources :strains
  root 'wines#index'






end

app/models/wine.rb
class Wine < ApplicationRecord
  has_many :wine_strains, dependent: :destroy
  has_many :strains, through: :wine_strains
  accepts_nested_attributes_for :wine_strains, reject_if: :all_blank, allow_destroy: true

    def strain_and_percent
    namepercen = []
    wine_strains.map do |winestrain|
        namepercen.push [winestrain.strain.name, winestrain.percentage] 
    end
    namepercen.sort_by{ |array| array[0] }.map do |strain|
        "#{strain[0]} (#{strain[1]})%"
    end.join(', ')
end

end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :set_wine, only: %i[ show edit update destroy ]

  # GET /wines or /wines.json
  def index
    @wines = Wine.all
  end

  # GET /wines/1 or /wines/1.json
  def show
  end

  # GET /wines/new
  def new
    @wine = Wine.new
    @strains = Strain.all
    @wine.wine_strains.build
  end

  # GET /wines/1/edit
  def edit
    @strains = Strain.all
  end

  # POST /wines or /wines.json
  def create
    @wine = Wine.new(wine_params)

    respond_to do |format|
      if @wine.save
        format.html { redirect_to @wine, notice: "Wine was successfully created." }
        format.json { render :show, status: :created, location: @wine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wines/1 or /wines/1.json
  def update
    respond_to do |format|
      if @wine.update(wine_params)
        format.html { redirect_to @wine, notice: "Wine was successfully updated." }
        format.json { render :show, status: :ok, location: @wine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1 or /wines/1.json
  def destroy
    @wine.destroy
    respond_to do |format|
      format.html { redirect_to wines_url, notice: "Wine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine
      @wine = Wine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wine_params
      params.require(:wine).permit(:name, :score, strain_attributes: [:id, :name], wine_strains_attributes: [:wine_id, :strain_id, :percentage])
    end
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/wines/_form.html.erb
<%= form_with(model: wine, local: true) do |form| %>
  <% if wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
      <% wine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <% @wine.id.present? %>
  <div class="field">
    <%= form.label :score %>
    <%= form.number_field :score %>
  </div>

  <div class="link">
    <%= link_to_add_association 'add strain', form, :wine_strains %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wines/_wine_strain_fields.html.erb
<div class="nested-fields">
    <div class="field">
        <%= f.label :strain_id %>
        <%= f.select :strain_id, options_from_collection_for_select(@strains, :id, :name) %>
    </div>
    <div class="field">
        <%= f.label :percentage %>
        <%= f.number_field :percentage %>    
    </div>
    <%= link_to_remove_association "remove strain", f %>
</div>

app/views/wines/edit.html.erb
<h1>Editing Wine</h1>
<%=  %>
<%= render 'form', wine: @wine %>

<%= link_to 'Show', @wine %> |
<%= link_to 'Back', wines_path %>

app/views/wines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wines</h1>

<table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Strain</th>
        <th>Score</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @wines.each do |wine| %>
        <tr>
          <td><%= wine.name%></td>
          <td><%=wine.strain_and_percent%></td>
          <td><%=wine.score%></td>        
          <td><%= link_to 'Show', wine %></td>
          <% if current_user.admin?  %>
          <td><%= link_to 'Edit', edit_wine_path(wine) %></td>
          <td><%= link_to 'Destroy', wine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end  %>
        </tr>
      <% end %>

    </tbody>
  </table>
  <br>
    <div>
    <% if current_user.admin?  %>
      <%= link_to 'New Wine', new_wine_path, class:'btn btn-dark text-primary' %>
      <%= link_to 'New Strain', new_strain_path, class:'btn btn-dark text-primary' %>
      <% end  %>
    </div>

app/views/wines/new.html.erb
<h1>New Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Back', wines_path %>

app/views/wines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wine.name %>
</p>

<%= link_to 'Edit', edit_wine_path(@wine) %> |
<%= link_to 'Back', wines_path %>